#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO


do_start () {

    mpv -fs -vo sdl /home/pi/RetroPie/splashscreens/splash-720p-only.mp4
    #/usr/bin/fbi -T 2 -once -noverbose -a /home/pi/RetroPie/splashscreens/splash.png &
    sleep 5
    #mplayer /home/pi/RetroPie/splashscreens/bootsnd.ogg
    python /home/pi/RetrOrangePi/Background_Music/bgmusic.py &
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
