INCLUDES=-I.

SRCS = WinSystemEGL.cpp
SRCS+= EGLNativeTypeAmlogic.cpp
ifeq (,1)
SRCS+= EGLNativeTypeAndroid.cpp
SRCS+= EGLNativeTypeAmlAndroid.cpp
endif
ifeq (,1)
SRCS+= EGLNativeTypeRaspberryPI.cpp
endif
ifeq (,1)
SRCS+= EGLNativeTypeIMX.cpp
endif
#SRCS+= EGLWrapper.cpp

LIB = windowing_egl.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
